### ISSUE TITLE
unable to upload mascot dat file from thermo pd for  analysis

### ISSUE THREAD

**Issue by GoogleCodeExporter** [compomics/fragmentation-analyzer#1]
```
What steps will reproduce the problem?
1.did mascot search in Proteome Discoverer paltform thermo
2.obtained dat file .
3.submitted dat file for fragmentation analysis

What is the expected output? What do you see instead?
file should have been uploaded, error message in the error log file
"Exception in thread "ImportThread" java.lang.NumberFormatException: null
    at java.lang.Long.parseLong(Unknown Source)
    at java.lang.Long.parseLong(Unknown Source)
    at com.compomics.mascotdatfile.util.mascot.Header.<init>(Header.java:101)
    at com.compomics.mascotdatfile.util.mascot.MascotDatfile_Index.getHeaderSection(MascotDatfile_Index.java:182)
    at com.compomics.mascotdatfile.util.mascot.MascotDatfile_Index.getNumberOfQueries(MascotDatfile_Index.java:252)
    at com.compomics.mascotdatfile.util.mascot.iterator.QueryEnumerator.<init>(QueryEnumerator.java:39)
    at com.compomics.mascotdatfile.util.mascot.MascotDatfile_Index.getQueryEnumerator(MascotDatfile_Index.java:390)
    at no.uib.fragmentation_analyzer.gui.DataSource.parseMascotDatFile(DataSource.java:1289)
    at no.uib.fragmentation_analyzer.gui.DataSource.access$1200(DataSource.java:62)
    at no.uib.fragmentation_analyzer.gui.DataSource$11.run(DataSource.java:660)
"

What version of the product are you using? On what operating system?
1.5.11, windows 7, i3 processor with 4 gb ram

Please provide any additional information below.


```

Original issue reported on code.google.com by `bhanu.ra...@gmail.com` on 6 May 2014 at 6:31

Attachments:
- [ErrorLog.zip](https://storage.googleapis.com/google-code-attachments/fragmentation-analyzer/issue-1/comment-0/ErrorLog.zip)

**Comment by hbarsnes** [comment]
Issue assume resolved by the user. If this is not the case, let us know and we'll reopen the issue.
